---
swagger: "2.0"
info:
  description: "This API enables the Metrics Service to post metrics measurements/events\
    \ to edge applications <p>**Micro-service**<br>None <p>**Type & Usage**<br>User's\
    \ Edge Applications subscribing to Metrics measurements/events must implement\
    \ this API <p>**Details**<br>API details available at _your-AdvantEDGE-ip-address:30000/api_\
    \ <p>**Default Port**<br>This API is not exposed by default on the AdvantEDGE\
    \ platform"
  version: "1.0.0"
  title: "AdvantEDGE Metrics Service Notification REST API"
  contact:
    name: "InterDigital AdvantEDGE Support"
    email: "AdvantEDGE@InterDigital.com"
  license:
    name: "Apache 2.0"
    url: "https://github.com/InterDigitalInc/AdvantEDGE/blob/master/LICENSE"
host: "172.0.0.1:8081"
basePath: "/metrics/v2"
tags:
- name: "notifications"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /network/{subscriptionId}:
    post:
      tags:
      - "notifications"
      summary: "This operation is used by the AdvantEDGE Metrics Service to issue\
        \ a callback notification towards an ME application with a Network Metrics\
        \ subscription"
      description: "Network metrics subscription notification"
      operationId: "postNetworkNotification"
      parameters:
      - name: "subscriptionId"
        in: "path"
        description: "Identity of a notification subscription"
        required: true
        type: "string"
        x-exportParamName: "SubscriptionId"
      - in: "body"
        name: "Notification"
        description: "Network Notification"
        required: true
        schema:
          $ref: "#/definitions/NetworkNotification"
        x-exportParamName: "Notification"
      responses:
        204:
          description: "No Content"
  /event/{subscriptionId}:
    post:
      tags:
      - "notifications"
      summary: "This operation is used by the AdvantEDGE Metrics Service to issue\
        \ a callback notification towards an ME application with an Event subscription"
      description: "Events subscription notification"
      operationId: "postEventNotification"
      parameters:
      - name: "subscriptionId"
        in: "path"
        description: "Identity of a notification subscription"
        required: true
        type: "string"
        x-exportParamName: "SubscriptionId"
      - in: "body"
        name: "Notification"
        description: "Event Notification"
        required: true
        schema:
          $ref: "#/definitions/EventNotification"
        x-exportParamName: "Notification"
      responses:
        204:
          description: "No Content"
definitions:
  EventMetrics:
    type: "object"
    properties:
      time:
        type: "string"
        example: "2019-11-24T12:45:00-5:00"
        description: "Time of event metrics"
      event:
        type: "string"
        example: "Mobility event ue1 to poa3"
        description: "Event description"
    description: "Value of a single event metric"
    example:
      description: "Mobility event ue1 to poa3"
      time: "2019-11-24T12:45:00-5:00"
  EventMetricsList:
    type: "object"
    properties:
      name:
        type: "string"
        example: "event metrics"
        description: "Response name"
      columns:
        type: "array"
        description: "columns included in response based on queried values"
        items:
          type: "string"
          example: "event"
          description: "Queried value"
      values:
        type: "array"
        items:
          $ref: "#/definitions/EventMetrics"
    description: "Event metrics query response"
    example:
      columns:
      - "lat,tput,loss"
      values:
      - event: "Mobility event ue1 to poa3"
        time: "2019-11-24T12:45:00-5:00"
      - event: "Mobility event ue1 to poa3"
        time: "2019-11-24T12:45:00-5:00"
      name: "event metrics"
  NetworkMetricsList:
    type: "object"
    properties:
      name:
        type: "string"
        example: "network metrics"
        description: "Response name"
      columns:
        type: "array"
        example: "time,lat,tput,loss"
        description: "columns included in response based on queried values"
        items:
          type: "string"
          example: "lat,tput,loss"
          description: "Queried value"
      values:
        type: "array"
        items:
          $ref: "#/definitions/NetworkMetrics"
    description: "Network metrics query response"
    example:
      columns: "time,lat,tput,loss"
      values:
      - loss: 0.003
        time: "2019-11-24T12:45:00-5:00"
        tput: 100000.0
        lat: 5.123
      - loss: 0.003
        time: "2019-11-24T12:45:00-5:00"
        tput: 100000.0
        lat: 5.123
      name: "network metrics"
  NetworkMetrics:
    type: "object"
    properties:
      time:
        type: "string"
        example: "2019-11-24T12:45:00-5:00"
        description: "Time of network value"
      lat:
        type: "number"
        format: "float"
        example: 5.123
        description: "Network latency (ms)"
      tput:
        type: "number"
        format: "float"
        example: 100000.0
        description: "Network throughput (Mbps)"
      loss:
        type: "number"
        format: "float"
        example: 0.003
        description: "Network packet loss (%)"
    description: "Value of a single network metric"
    example:
      loss: 0.003
      time: "2019-11-24T12:45:00-5:00"
      tput: 100000.0
      lat: 5.123
  SubscriptionId:
    type: "string"
    description: "Unique Identifier for a notification subscription.  Created by the\
      \ MEC Metrics Service and used to reference an individual subscription"
    example: "sub123"
  EventNotification:
    type: "object"
    required:
    - "callbackData"
    properties:
      callbackData:
        type: "string"
        example: "1234"
        description: "CallBackData if passed by the application during the associated\
          \ Event Subscription operation."
      eventMetricsList:
        $ref: "#/definitions/EventMetricsList"
    description: "Event notification - callback generated toward an ME app with an\
      \ event subscription"
    example:
      callbackData: "1234"
      eventMetricsList:
        columns:
        - "time,event"
        values:
        - event: "Mobility event ue1 to poa3"
          time: "2019-11-24T12:45:00-5:00"
        - event: "Mobility event ue1 to poa3"
          time: "2019-11-24T12:45:00-5:00"
        name: "event metrics"
  NetworkNotification:
    type: "object"
    required:
    - "callbackData"
    properties:
      callbackData:
        type: "string"
        example: "1234"
        description: "CallBackData if passed by the application during the associated\
          \ Network Subscription operation."
      networkMetricsList:
        $ref: "#/definitions/NetworkMetricsList"
    description: "Network notification - callback generated toward an ME app with\
      \ a network subscription"
    example:
      callbackData: "1234"
      networkMetricsList:
        columns: "time,lat,tput,loss"
        values:
        - loss: 0.003
          time: "2019-11-24T12:45:00-5:00"
          tput: 100000.0
          lat: 5.123
        - loss: 0.003
          time: "2019-11-24T12:45:00-5:00"
          tput: 100000.0
          lat: 5.123
        name: "network metrics"
parameters:
  Path.SubscriptionId:
    name: "subscriptionId"
    in: "path"
    description: "Identity of a notification subscription (network or event)"
    required: true
    type: "string"
    x-exportParamName: "SubscriptionId"
  Body.NetworkNotification:
    in: "body"
    name: "Notification"
    description: "Network Metrics Notification"
    required: true
    schema:
      $ref: "#/definitions/NetworkNotification"
    x-exportParamName: "Notification"
  Body.EventNotification:
    in: "body"
    name: "Notification"
    description: "Events Notification"
    required: true
    schema:
      $ref: "#/definitions/EventNotification"
    x-exportParamName: "Notification"
externalDocs:
  description: "GitHub Wiki"
  url: "https://github.com/InterDigitalInc/AdvantEDGE/wiki"
