---
swagger: "2.0"
info:
  description: "This is the MEEP Demo App API"
  version: "0.0.1"
  title: "MEEP Demo App API"
  termsOfService: "InterDigital Internal Only"
host: "127.0.0.1:8086"
basePath: "/v1"
tags:
- name: "Edge App Info"
- name: "UE State"
- name: "State Transfer"
- name: "UE Location"
- name: "Notifications"
  description: "AdvantEDGE Location Subscription Notification Callbacks (user and\
    \ zonal)"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /edge-app:
    get:
      tags:
      - "Edge App Info"
      summary: "Retrieve edge add info"
      description: ""
      operationId: "getEdgeInfo"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/EdgeInfo"
        404:
          description: "Not found"
  /ue/{ueId}:
    get:
      tags:
      - "UE State"
      summary: "Retrieves the UE state values"
      description: ""
      operationId: "getUeState"
      produces:
      - "application/json"
      parameters:
      - name: "ueId"
        in: "path"
        description: "UE identifier"
        required: true
        type: "string"
        x-exportParamName: "UeId"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UeState"
        400:
          description: "Bad request"
        404:
          description: "Not found"
    post:
      tags:
      - "UE State"
      summary: "Registers the UE and starts a counter"
      description: ""
      operationId: "createUeState"
      produces:
      - "application/json"
      parameters:
      - name: "ueId"
        in: "path"
        description: "UE identifier"
        required: true
        type: "string"
        x-exportParamName: "UeId"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        500:
          description: "Intenal server error"
  /mg/event:
    post:
      tags:
      - "State Transfer"
      summary: "Send event notification to registered Mobility Group Application"
      description: ""
      operationId: "handleEvent"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "event"
        description: "Mobility Group event notification"
        required: true
        schema:
          $ref: "#/definitions/MobilityGroupEvent"
        x-exportParamName: "Event"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        404:
          description: "Not found"
  /location/{ueId}:
    get:
      tags:
      - "UE Location"
      summary: "Retrieves the UE location values"
      description: ""
      operationId: "getUeLocation"
      produces:
      - "application/json"
      parameters:
      - name: "ueId"
        in: "path"
        description: "UE identifier"
        required: true
        type: "string"
        x-exportParamName: "UeId"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UserInfo"
        400:
          description: "Bad request"
        404:
          description: "Not found"
  /location_notifications/{subscriptionId}:
    post:
      tags:
      - "Notifications"
      summary: "This operation is used by the AdvantEDGE Location Service to issue\
        \ a callback notification towards an ME application with a zonal or user tracking\
        \ subscription"
      description: "Zonal or User location tracking subscription notification"
      operationId: "RcvTrackingNotification"
      parameters:
      - name: "subscriptionId"
        in: "path"
        description: "Identity of a notification subscription (user or zonal)"
        required: true
        type: "string"
        x-exportParamName: "SubscriptionId"
      - in: "body"
        name: "Notification"
        description: "Zonal or User Tracking Notification"
        required: true
        schema:
          $ref: "#/definitions/TrackingNotification"
        x-exportParamName: "Notification"
      responses:
        204:
          description: "No Content"
definitions:
  EdgeInfo:
    type: "object"
    properties:
      svc:
        type: "string"
        description: "Edge app service"
      name:
        type: "string"
        description: "Edge app local name"
      ip:
        type: "string"
        description: "IP address where the local edge app reside"
    description: "Edge app basic information object"
    example:
      edgeInfo:
      - svc: "game"
        name: "edge1-zone1-game"
        ip: "10.32.0.13"
  MobilityGroupAppState:
    type: "object"
    properties:
      ueId:
        type: "string"
        description: "Mobility Group UE Identifier"
      ueState:
        type: "string"
        description: "Mobility Group Application State for provided UE"
    description: "Mobility Group Application State"
    example:
      ueState: "ueState"
      ueId: "ueId"
  MobilityGroupEvent:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Mobility Group event name"
      type:
        type: "string"
        description: "Mobility Group event type"
        enum:
        - "STATE-UPDATE"
        - "STATE-TRANSFER-START"
        - "STATE-TRANSFER-COMPLETE"
        - "STATE-TRANSFER-CANCEL"
      ueId:
        type: "string"
        description: "Mobility Group UE identifier"
      appState:
        $ref: "#/definitions/MobilityGroupAppState"
    description: "Event object"
    example:
      appState:
        ueState: "ueState"
        ueId: "ueId"
      name: "name"
      type: "STATE-UPDATE"
      ueId: "ueId"
  UeState:
    type: "object"
    properties:
      duration:
        type: "integer"
        description: "Duration since the game stated"
    description: "Ue state basic information object"
    example:
      ueState:
      - duration: 32
  AccessPointId:
    type: "string"
    description: "Unique identifier of a point of access"
    example: "001010000000000000000000000000001 or poa001"
  Address:
    type: "string"
    description: "Address of the user or device based on the connected access point\
      \ - address = acr:<UE IP address>"
    example: "acr:10.1.34.67"
  CallbackData:
    type: "string"
    description: "CallBackData if passed by the application during the associated\
      \ Subscription (Zone or User Tracking) operation"
    example: "1234"
  InterestRealm:
    type: "string"
    description: "Details about the access point, geographical position, industry,\
      \ etc."
    example: "NY"
  NumberOfAccessPoints:
    type: "integer"
    format: "uint32"
    description: "Number of access points or points of access within a Location Zone"
    example: "10"
  NumberOfUsers:
    type: "integer"
    format: "uint32"
    description: "The number of users currently on the access point"
    example: "7"
  ResourceURL:
    type: "string"
    format: "url"
    description: "URL where the UE may be contacted for some service (application\
      \ specific)"
    example: "http://172.1.19.2:8081/myService/123456"
  SubscriptionId:
    type: "string"
    description: "Unique Identifier for a notification subscription.  Created by the\
      \ MEC Location Service and used to reference an individual subscription"
    example: "sub123"
  Timestamp:
    type: "string"
    format: "date-time"
    description: "Indicates the time of day for zonal presence notification."
  UserId:
    type: "string"
    description: "Unique identifier of a user or client node"
    example: "client001"
  UserInfo:
    type: "object"
    required:
    - "accessPointId"
    - "address"
    - "resourceURL"
    - "zoneId"
    properties:
      userId:
        $ref: "#/definitions/UserId"
      address:
        $ref: "#/definitions/Address"
      accessPointId:
        $ref: "#/definitions/AccessPointId"
      zoneId:
        $ref: "#/definitions/ZoneId"
      resourceURL:
        $ref: "#/definitions/ResourceURL"
    example:
      address: "acr:10.1.34.67"
      resourceURL: "http://172.1.19.2:8081/myService/123456"
      accessPointId: "001010000000000000000000000000001 or poa001"
      zoneId: "zone001"
      userId: "client001"
  UserList:
    type: "object"
    required:
    - "userList"
    properties:
      userList:
        type: "array"
        items:
          $ref: "#/definitions/UserInfo"
  UserEventType:
    type: "string"
    enum:
    - "Entering"
    - "Transferring"
    - "Exiting"
  UserTrackingNotification:
    type: "object"
    required:
    - "callbackData"
    - "timeStamp"
    - "userInfo"
    properties:
      callbackData:
        $ref: "#/definitions/CallbackData"
      userInfo:
        $ref: "#/definitions/UserInfo"
      timeStamp:
        $ref: "#/definitions/Timestamp"
      userEventType:
        $ref: "#/definitions/UserEventType"
    description: "User tracking notification - callback generated toward an ME app\
      \ with a user tracking subscription"
  ZoneId:
    type: "string"
    description: "Unique Identifier of a Location Zone"
    example: "zone001"
  ZoneInfo:
    type: "object"
    required:
    - "numberOfAccessPoints"
    - "numberOfUsers"
    - "zoneId"
    properties:
      zoneId:
        $ref: "#/definitions/ZoneId"
      numberOfAccessPoints:
        $ref: "#/definitions/NumberOfAccessPoints"
      numberOfUsers:
        $ref: "#/definitions/NumberOfUsers"
    description: "A type containing zone information."
  TrackingNotification:
    type: "object"
    required:
    - "callbackData"
    properties:
      callbackData:
        $ref: "#/definitions/CallbackData"
      zoneId:
        $ref: "#/definitions/ZoneId"
      address:
        $ref: "#/definitions/Address"
      interestRealma:
        $ref: "#/definitions/InterestRealm"
      userEventType:
        $ref: "#/definitions/UserEventType"
      currentAccessPointId:
        $ref: "#/definitions/AccessPointId"
      previousAccessPointId:
        $ref: "#/definitions/AccessPointId"
      timestamp:
        $ref: "#/definitions/Timestamp"
    description: "Zonal or User tracking notification - callback generated toward\
      \ an ME app with a zonal or user tracking subscription"
    example:
      address: "acr:10.1.34.67"
      userEventType: {}
      callbackData: "1234"
      previousAccessPointId: "001010000000000000000000000000001 or poa001"
      zoneId: "zone001"
      interestRealma: "NY"
      currentAccessPointId: "001010000000000000000000000000001 or poa001"
      timestamp: "2017-01-01T02:51:43Z"
parameters:
  Path.UeId:
    name: "ueId"
    in: "path"
    description: "Identity of a ue, refered to as ue id"
    required: true
    type: "string"
  event:
    in: "body"
    name: "event"
    description: "Mobility Group event notification"
    required: true
    schema:
      $ref: "#/definitions/MobilityGroupEvent"
    x-exportParamName: "Event"
  Path.SubscriptionId:
    name: "subscriptionId"
    in: "path"
    description: "Identity of a notification subscription (user or zonal)"
    required: true
    type: "string"
    x-exportParamName: "SubscriptionId"
  Body.TrackingNotification:
    in: "body"
    name: "Notification"
    description: "Zonal or User Tracking Notification"
    required: true
    schema:
      $ref: "#/definitions/TrackingNotification"
    x-exportParamName: "Notification"
responses:
  Std200:
    description: "OK"
  Std201:
    description: "Created"
  Std202:
    description: "Accepted"
  Std204:
    description: "No content"
  Std304:
    description: "Not modified"
  Std400:
    description: "Bad request"
  Std401:
    description: "Not authorized"
  Std403:
    description: "Forbidden"
  Std404:
    description: "Not found"
  Std409:
    description: "Conflict"
  Std416:
    description: "Requested range not satisfiable"
  Std500:
    description: "Internal server error"
externalDocs:
  description: "Find out more about MEEP Demo App API"
  url: "http://www.localinfo/pdf"
